#!/usr/bin/env python3
"""
Clean Security CSV File - Remove Invalid Model References

This script removes all entries from ir.model.access.csv that reference
models that don't exist in the records_management module.
"""

import os
import csv
import re

def extract_model_names_from_init():
    """Extract model names from models/__init__.py"""
    init_file = "/Users/johncope/Documents/ssh-git-github.com-odoo-odoo.git-18.0/records_management/models/__init__.py"

    model_names = set()

    with open(init_file, 'r') as f:
        content = f.read()

    # Find all import statements
    import_pattern = r'from \. import \((.*?)\)'
    import_match = re.search(import_pattern, content, re.DOTALL)

    if import_match:
        imports_block = import_match.group(1)

        # Split by commas and clean up
        imports = [line.strip().rstrip(',') for line in imports_block.split('\n') if line.strip()]

        for import_line in imports:
            # Remove comments
            if '#' in import_line:
                import_line = import_line.split('#')[0].strip()

            if import_line:
                # Convert filename to model name (remove .py extension)
                model_name = import_line.replace('.py', '')
                # Convert to Odoo model name format
                if model_name:
                    model_names.add(f'records_management.{model_name}')

    # Add some known core models that might be referenced
    core_models = {
        'res.users',
        'res.partner',
        'res.company',
        'product.product',
        'product.template',
        'account.move',
        'account.move.line',
        'stock.picking',
        'stock.move',
        'stock.lot',
        'project.task',
        'hr.employee',
        'mail.message',
        'mail.activity',
        'ir.attachment',
        'ir.model',
        'ir.model.fields',
        'ir.ui.view',
        'ir.ui.menu',
        'ir.actions.act_window',
        'ir.rule',
        'base',
        'portal',
        'website',
        'sign',
        'sms',
        'survey',
        'maintenance',
        'quality',
        'industry_fsm',
        'point_of_sale',
        'sale',
        'purchase',
        'account',
        'stock',
        'mrp',
        'crm',
        'hr',
        'calendar',
        'note',
        'mail',
        'web',
        'base_setup',
        'auth_signup',
        'auth_totp',
        'web_tour',
        'bus',
        'im_livechat',
        'rating',
        'digest',
        'iap',
        'payment',
        'l10n_generic_coa',
        'uom',
        'decimal_precision',
        'report',
        'board',
        'contacts',
        'gamification',
        'google_account',
        'google_gmail',
        'google_calendar',
        'microsoft_account',
        'microsoft_calendar',
        'microsoft_outlook',
        'snailmail',
        'social',
        'utm',
        'web_editor',
        'web_unsplash',
        'website_sale',
        'website_blog',
        'website_event',
        'website_forum',
        'website_slides',
        'website_theme_install',
        'account_asset',
        'account_budget',
        'account_check_printing',
        'account_payment',
        'account_reconcile',
        'account_reports',
        'account_tax_python',
        'analytic',
        'asset',
        'barcodes',
        'board',
        'calendar_sms',
        'contacts',
        'crm_iap_mining',
        'crm_phone_validation',
        'currency_rate_live',
        'data_cleaning',
        'delivery',
        'documents',
        'event',
        'event_booth',
        'event_sale',
        'fleet',
        'gamification',
        'google_recaptcha',
        'helpdesk',
        'hr_appraisal',
        'hr_attendance',
        'hr_contract',
        'hr_expense',
        'hr_holidays',
        'hr_org_chart',
        'hr_payroll',
        'hr_recruitment',
        'hr_skills',
        'hr_timesheet',
        'http_routing',
        'iap',
        'iap_crm',
        'iap_mail',
        'knowledge',
        'l10n_ar',
        'l10n_au',
        'l10n_be',
        'l10n_br',
        'l10n_ca',
        'l10n_ch',
        'l10n_cl',
        'l10n_cn',
        'l10n_co',
        'l10n_cr',
        'l10n_cz',
        'l10n_de',
        'l10n_dk',
        'l10n_do',
        'l10n_ec',
        'l10n_ee',
        'l10n_es',
        'l10n_et',
        'l10n_fi',
        'l10n_fr',
        'l10n_gb',
        'l10n_gr',
        'l10n_gt',
        'l10n_hk',
        'l10n_hr',
        'l10n_hu',
        'l10n_id',
        'l10n_ie',
        'l10n_il',
        'l10n_in',
        'l10n_it',
        'l10n_jp',
        'l10n_ke',
        'l10n_kr',
        'l10n_lt',
        'l10n_lu',
        'l10n_lv',
        'l10n_ma',
        'l10n_mx',
        'l10n_my',
        'l10n_nl',
        'l10n_no',
        'l10n_nz',
        'l10n_pe',
        'l10n_ph',
        'l10n_pl',
        'l10n_pt',
        'l10n_ro',
        'l10n_sa',
        'l10n_se',
        'l10n_sg',
        'l10n_si',
        'l10n_sk',
        'l10n_th',
        'l10n_tr',
        'l10n_tw',
        'l10n_ua',
        'l10n_us',
        'l10n_ve',
        'l10n_vn',
        'l10n_za',
        'l10n_zh',
        'mail_bot',
        'mail_group',
        'mass_mailing',
        'mass_mailing_sms',
        'membership',
        'microsoft_account',
        'microsoft_calendar',
        'microsoft_outlook',
        'mrp',
        'mrp_account',
        'mrp_plm',
        'mrp_subcontracting',
        'mrp_workorder',
        'note',
        'payment',
        'payment_adyen',
        'payment_alipay',
        'payment_authorize',
        'payment_buckaroo',
        'payment_mollie',
        'payment_ogone',
        'payment_paypal',
        'payment_payulatam',
        'payment_payumoney',
        'payment_sips',
        'payment_stripe',
        'payment_transfer',
        'phone_validation',
        'planning',
        'pos_cache',
        'pos_daily_sales_reports',
        'pos_discount',
        'pos_epson_printer',
        'pos_hr',
        'pos_iot',
        'pos_loyalty',
        'pos_mercury',
        'pos_online_payment',
        'pos_paytm',
        'pos_restaurant',
        'pos_six',
        'pos_stripe',
        'privacy_lookup',
        'procurement',
        'product',
        'product_expiry',
        'product_margin',
        'product_packaging',
        'project',
        'project_forecast',
        'project_hr_expense',
        'project_mrp',
        'project_purchase',
        'project_sms',
        'purchase',
        'purchase_price_diff',
        'purchase_requisition',
        'purchase_stock',
        'rating',
        'repair',
        'report_xlsx',
        'resource',
        'sale',
        'sale_coupon',
        'sale_expense',
        'sale_loyalty',
        'sale_management',
        'sale_margin',
        'sale_order_dates',
        'sale_product_configurator',
        'sale_project',
        'sale_purchase',
        'sale_renting',
        'sale_sms',
        'sale_stock',
        'sale_subscription',
        'sale_timesheet',
        'sale_tour',
        'sap',
        'social_facebook',
        'social_instagram',
        'social_linkedin',
        'social_twitter',
        'social_youtube',
        'stock',
        'stock_account',
        'stock_barcode',
        'stock_dropshipping',
        'stock_landed_costs',
        'stock_picking_batch',
        'stock_production_lot',
        'stock_sms',
        'stock_valuation',
        'subscription',
        'survey',
        'test_convert',
        'test_impex',
        'test_lint',
        'test_mail',
        'test_new_api',
        'test_performance',
        'test_website',
        'theme_common',
        'theme_default',
        'transifex',
        'uom',
        'utm',
        'web',
        'web_editor',
        'web_gantt',
        'web_kanban',
        'web_mobile',
        'web_tour',
        'website',
        'website_blog',
        'website_cookie_notice',
        'website_crm',
        'website_customer',
        'website_event',
        'website_event_booth',
        'website_event_exhibitor',
        'website_event_meeting',
        'website_event_questions',
        'website_event_track',
        'website_event_track_live',
        'website_event_track_quiz',
        'website_form',
        'website_forum',
        'website_helpdesk',
        'website_helpdesk_livechat',
        'website_helpdesk_slides',
        'website_hr_recruitment',
        'website_jitsi',
        'website_livechat',
        'website_mail',
        'website_mass_mailing',
        'website_membership',
        'website_payment',
        'website_planner',
        'website_sale',
        'website_sale_comparison',
        'website_sale_coupon',
        'website_sale_delivery',
        'website_sale_digital',
        'website_sale_loyalty',
        'website_sale_renting',
        'website_sale_stock',
        'website_sale_subscription',
        'website_sale_wishlist',
        'website_slides',
        'website_theme_install',
        'website_twitter_wall',
        'webhook',
        'whatsapp',
        'wkhtmltopdf',
        'work',
        'xlsxwriter',
        'account_followup',
        'account_lock',
        'account_taxcloud',
        'analytic_accounting',
        'auth_ldap',
        'auth_oauth',
        'auth_password_policy',
        'auth_session_timeout',
        'base_automation',
        'base_gengo',
        'base_geolocalize',
        'base_import',
        'base_sparse_field',
        'base_technical_features',
        'base_vat',
        'board',
        'calendar',
        'contacts',
        'crm',
        'crm_livechat',
        'crm_reveal',
        'data_recycle',
        'delivery_bpost',
        'delivery_dhl',
        'delivery_fedex',
        'delivery_ups',
        'delivery_usps',
        'documents_account',
        'documents_hr',
        'documents_product',
        'documents_project',
        'documents_spreadsheet',
        'event',
        'event_crm',
        'event_sale',
        'event_sms',
        'fetchmail',
        'fleet',
        'gamification',
        'google_account',
        'google_calendar',
        'google_drive',
        'google_gmail',
        'google_spreadsheet',
        'hr_appraisal',
        'hr_attendance',
        'hr_contract',
        'hr_expense',
        'hr_fleet',
        'hr_gamification',
        'hr_holidays',
        'hr_maintenance',
        'hr_org_chart',
        'hr_payroll',
        'hr_recruitment',
        'hr_referral',
        'hr_skills',
        'hr_timesheet',
        'hr_work_entry',
        'hr_work_entry_contract',
        'http_routing',
        'im_livechat',
        'im_support',
        'knowledge',
        'mail',
        'mail_bot',
        'mail_group',
        'mail_template',
        'mass_mailing',
        'mass_mailing_crm',
        'mass_mailing_event',
        'mass_mailing_sale',
        'mass_mailing_sms',
        'mass_mailing_themes',
        'membership',
        'microsoft_account',
        'microsoft_calendar',
        'microsoft_outlook',
        'mrp',
        'mrp_account',
        'mrp_bom',
        'mrp_plm',
        'mrp_repair',
        'mrp_subcontracting',
        'mrp_workorder',
        'note',
        'pad',
        'partner_autocomplete',
        'payment',
        'payment_adyen',
        'payment_alipay',
        'payment_authorize',
        'payment_buckaroo',
        'payment_mollie',
        'payment_ogone',
        'payment_paypal',
        'payment_payulatam',
        'payment_payumoney',
        'payment_sips',
        'payment_stripe',
        'payment_transfer',
        'phone_validation',
        'planning',
        'pos_cache',
        'pos_daily_sales_reports',
        'pos_discount',
        'pos_epson_printer',
        'pos_hr',
        'pos_iot',
        'pos_loyalty',
        'pos_mercury',
        'pos_online_payment',
        'pos_paytm',
        'pos_restaurant',
        'pos_six',
        'pos_stripe',
        'privacy_lookup',
        'procurement',
        'product',
        'product_email_template',
        'product_expiry',
        'product_margin',
        'product_packaging',
        'project',
        'project_account',
        'project_forecast',
        'project_hr_expense',
        'project_mrp',
        'project_purchase',
        'project_sms',
        'purchase',
        'purchase_price_diff',
        'purchase_requisition',
        'purchase_stock',
        'rating',
        'repair',
        'report_xlsx',
        'resource',
        'sale',
        'sale_coupon',
        'sale_expense',
        'sale_loyalty',
        'sale_management',
        'sale_order_dates',
        'sale_product_configurator',
        'sale_project',
        'sale_purchase',
        'sale_renting',
        'sale_sms',
        'sale_stock',
        'sale_subscription',
        'sale_timesheet',
        'sale_tour',
        'sap',
        'social_facebook',
        'social_instagram',
        'social_linkedin',
        'social_twitter',
        'social_youtube',
        'stock',
        'stock_account',
        'stock_barcode',
        'stock_dropshipping',
        'stock_landed_costs',
        'stock_picking_batch',
        'stock_production_lot',
        'stock_sms',
        'stock_valuation',
        'subscription',
        'survey',
        'test_convert',
        'test_impex',
        'test_lint',
        'test_mail',
        'test_new_api',
        'test_performance',
        'test_website',
        'theme_common',
        'theme_default',
        'transifex',
        'uom',
        'utm',
        'web',
        'web_editor',
        'web_gantt',
        'web_kanban',
        'web_mobile',
        'web_tour',
        'website',
        'website_blog',
        'website_cookie_notice',
        'website_crm',
        'website_customer',
        'website_event',
        'website_event_booth',
        'website_event_exhibitor',
        'website_event_meeting',
        'website_event_questions',
        'website_event_track',
        'website_event_track_live',
        'website_event_track_quiz',
        'website_form',
        'website_forum',
        'website_helpdesk',
        'website_helpdesk_livechat',
        'website_helpdesk_slides',
        'website_hr_recruitment',
        'website_jitsi',
        'website_livechat',
        'website_mail',
        'website_mass_mailing',
        'website_membership',
        'website_payment',
        'website_planner',
        'website_sale',
        'website_sale_comparison',
        'website_sale_coupon',
        'website_sale_delivery',
        'website_sale_digital',
        'website_sale_loyalty',
        'website_sale_renting',
        'website_sale_stock',
        'website_sale_subscription',
        'website_sale_wishlist',
        'website_slides',
        'website_theme_install',
        'website_twitter_wall',
        'webhook',
        'whatsapp',
        'wkhtmltopdf',
        'work',
        'xlsxwriter'
    }

    model_names.update(core_models)

    return model_names

def clean_security_csv():
    """Clean the security CSV file by removing invalid model references"""
    csv_file = "/Users/johncope/Documents/ssh-git-github.com-odoo-odoo.git-18.0/records_management/security/ir.model.access.csv"
    backup_file = csv_file + ".backup"

    # Get valid model names
    valid_models = extract_model_names_from_init()
    print(f"Found {len(valid_models)} valid models")

    # Read the CSV file
    cleaned_rows = []
    removed_count = 0

    with open(csv_file, 'r') as f:
        reader = csv.reader(f)
        header = next(reader)  # Skip header
        cleaned_rows.append(header)

        for row in reader:
            if len(row) >= 4:  # Ensure row has enough columns
                model_name = row[3]  # Model name is in column 4 (0-indexed)

                # Check if model exists
                if model_name in valid_models:
                    cleaned_rows.append(row)
                else:
                    removed_count += 1
                    print(f"Removing invalid model reference: {model_name}")

    # Create backup
    if os.path.exists(csv_file):
        os.rename(csv_file, backup_file)
        print(f"Created backup: {backup_file}")

    # Write cleaned CSV
    with open(csv_file, 'w', newline='') as f:
        writer = csv.writer(f)
        writer.writerows(cleaned_rows)

    print(f"Cleaned CSV file: removed {removed_count} invalid entries")
    print(f"Kept {len(cleaned_rows) - 1} valid entries")  # -1 for header

if __name__ == "__main__":
    clean_security_csv()
