version: '3'
services:
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    restart: always

  odoo:
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      # Ensure the 'records_management' directory exists at the project root or update the path below to an absolute path if needed
      - ./records_management:/mnt/extra-addons/records_management
    environment:
      - HOST=db
      - USER=odoo
restart: always
# /mnt/extra-addons/records_management/__manifest__.py
