version: '3.7'

services:
  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8069:8069"
    volumes:
      - ./custom_addons:/mnt/extra-addons
    environment:
      - HOST=0.0.0.0
      - PORT=8069

  postgres:
    image: postgres:10
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-db-data:
