version: '3'
services:
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    restart: always

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./addons/8.0:/mnt/extra-addons/official_addons
      - ./records_management:/mnt/extra-addons/records_management
    environment:
      - HOST=db
      - USER=odoo
    entrypoint: ["/entrypoint.sh"]
    restart: always
