version: '2'
services:
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    restart: always

  odoo:
    image: odoo:8.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./records_management:/mnt/extra-addons/records_management
    environment:
      - HOST=db
      - USER=
      
      - PASSWORD=odoo
    restart: always
