# pyproject.toml

[tool.black]
line-length = 79
target-version = ['py310']

[tool.isort]
profile = "black"
known_first_party = ["odoo"]
line_length = 79
force_single_line = true
combine_as_imports = true
include_trailing_comma = false
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
