{
    "name": "Records Management FSM Integration",
    "version": "18.0.1.0.0",
    "category": "Records Management",
    "summary": "FSM integration for Records Management",
    "author": "Your Name",
    "license": "LGPL-3",
    "depends": ["records_management", "industry_fsm", "project"],
    "data": [
        "data/fsm_model_external_ids_data.xml",
        "security/ir.model.access.csv",
        "views/enhanced_fsm_integration_views.xml",
        "views/fleet_fsm_integration_menus.xml",
        "views/fsm_notification_manager_views.xml",
        "views/fsm_notification_views.xml",
        "views/fsm_reschedule_wizard_placeholder_views.xml",
        "views/fsm_reschedule_wizard_views.xml",
        "views/fsm_task_service_line_views.xml",
        "views/fsm_task_views.xml",
        "views/mobile_fsm_integration_views.xml",
    ],
    "installable": True,
    # Auto-install so it comes in automatically with records_management + industry_fsm
    "auto_install": True,
}
