#!/bin/bash
# Automated XML field fixes based on validation results
# Generated by Advanced XML-to-Model Field Validator

# Fix: shredding.service.naid_compliant → location_id
sed -i 's/name="naid_compliant"/name="location_id"/g' records_management/demo_records.xml

# Fix: shredding.service.certificate_required → requires_certificate
sed -i 's/name="certificate_required"/name="requires_certificate"/g' records_management/demo_records.xml
