#!/bin/bash
# Automated XML field fixes based on validation results
# Generated by Advanced XML-to-Model Field Validator

# Fix: records.container.customer_id → partner_id
sed -i 's/name="customer_id"/name="partner_id"/g' records_management/odoo.xml

# Fix: records.location.climate_controlled → parent_location_id
sed -i 's/name="climate_controlled"/name="parent_location_id"/g' records_management/demo_records.xml

# Fix: records.location.climate_controlled → parent_location_id
sed -i 's/name="climate_controlled"/name="parent_location_id"/g' records_management/demo_records.xml

# Fix: records.container.container_type → container_type_id
sed -i 's/name="container_type"/name="container_type_id"/g' records_management/demo_records.xml

# Fix: records.container.height → weight
sed -i 's/name="height"/name="weight"/g' records_management/demo_records.xml

# Fix: records.container.container_type → container_type_id
sed -i 's/name="container_type"/name="container_type_id"/g' records_management/demo_records.xml

# Fix: records.container.height → weight
sed -i 's/name="height"/name="weight"/g' records_management/demo_records.xml

# Fix: shredding.service.naid_compliant → location_id
sed -i 's/name="naid_compliant"/name="location_id"/g' records_management/demo_records.xml

# Fix: shredding.service.certificate_required → requires_certificate
sed -i 's/name="certificate_required"/name="requires_certificate"/g' records_management/demo_records.xml
