from . import scrm_records_management
from . import customer_inventory_report
from . import pickup_request
from . import shredding_service
from . import stock_picking
from . import stock_lot
from . import stock_move_sms_validation
from . import ir_module
from . import ir_actions_report
from . import installer
