# -*- coding: utf-8 -*-
# Invoice Generation Log Model

from odoo import api, fields, models


class InvoiceGenerationLog(models.Model):
    """Log for invoice generation processes"""

    _name = "invoice.generation.log"
    _description = "Invoice Generation Log"
    _inherit = ["mail.thread", "mail.activity.mixin"]
    _order = "config_id, generation_date desc"

    config_id = fields.Many2one(
        "records.billing.config",
        string="Billing Config",
        required=True,
        ondelete="cascade",
    )
    generation_date = fields.Datetime(
        string="Generation Date", required=True, default=fields.Datetime.now
    )
    invoice_id = fields.Many2one("account.move", string="Generated Invoice")
    status = fields.Selection(
        [("success", "Success"), ("failed", "Failed"), ("pending", "Pending")],
        string="Status",
        default="pending",
    )
    error_message = fields.Text(string="Error Message")
    amount = fields.Monetary(string="Invoice Amount", currency_field="currency_id")
    currency_id = fields.Many2one(
        "res.currency",
        string="Currency",
        default=lambda self: self.env.company.currency_id,
    )
    generated_by_id = fields.Many2one(
        "res.users", string="Generated By", default=lambda self: self.env.user
    )
