from odoo import models, fields, api, _


class InvoiceGenerationLog(models.Model):
    _name = 'invoice.generation.log'
    _description = 'Invoice Generation Log'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _order = 'generation_date desc, id desc'

    # ============================================================================
    # FIELDS
    # ============================================================================
    name = fields.Char(string="Log Reference", required=True, copy=False, readonly=True, default=lambda self: _('New'))
    active = fields.Boolean(default=True)
    company_id = fields.Many2one('res.company', string='Company', required=True, default=lambda self: self.env.company)

    config_id = fields.Many2one('advanced.billing', string="Billing Configuration", readonly=True)
    generation_date = fields.Datetime(string="Generation Date", required=True, default=fields.Datetime.now, readonly=True)

    invoice_id = fields.Many2one('account.move', string="Generated Invoice", readonly=True)
    partner_id = fields.Many2one(related='invoice_id.partner_id', string="Customer", store=True, readonly=True)

    status = fields.Selection([
        ('success', 'Success'),
        ('failure', 'Failure'),
        ('warning', 'Warning')
    ], string='Status', required=True, default='failure', readonly=True)

    error_message = fields.Text(string='Log Message', readonly=True)
    amount = fields.Monetary(string='Invoice Amount', related='invoice_id.amount_total', readonly=True)
    currency_id = fields.Many2one('res.currency', related='company_id.currency_id', readonly=True)
    generated_by_id = fields.Many2one('res.users', string="Generated By", default=lambda self: self.env.user, readonly=True)

    # ============================================================================
    # ORM OVERRIDES
    # ============================================================================
    @api.model_create_multi
    def create(self, vals_list):
        """Override create to add auto-numbering for the log reference."""
        for vals in vals_list:
            if vals.get('name', _('New')) == _('New'):
                vals['name'] = self.env['ir.sequence'].next_by_code('invoice.generation.log') or _('New')
        return super().create(vals_list)

    # ============================================================================
    # ACTION METHODS
    # ============================================================================
    def action_view_invoice(self):
        """Redirect to the generated invoice form view."""
        self.ensure_one()
        if not self.invoice_id:
            return
        return {
            'type': 'ir.actions.act_window',
            'res_model': 'account.move',
            'view_mode': 'form',
            'res_id': self.invoice_id.id,
            'target': 'current',
        }
