from odoo import api, fields, models, _
from odoo.exceptions import ValidationError

# Note: Translation warnings during module loading are expected
# for constraint definitions - this is non-blocking behavior



class PortalBarcode(models.Model):
    _name = 'portal.barcode'
    _description = 'Portal Generated Barcode'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _order = 'id desc'

    name = fields.Char(string='Barcode', required=True, index=True, tracking=True, copy=False)
    state = fields.Selection([
        ('active', 'Active'),
        ('inactive', 'Inactive'),
        ('expired', 'Expired'),
    ], string='Status', default='active', tracking=True, required=True)
    barcode_format = fields.Selection([
        ('code128', 'Code 128'),
        ('ean13', 'EAN-13'),
        ('qrcode', 'QR Code'),
    ], string='Format', default='code128', required=True)
    barcode_type = fields.Selection([
        ('generic', 'Generic'),
        ('container', 'Container'),
        ('location', 'Location'),
        ('document', 'Document'),
        ('box', 'Storage Box'),
    ], string='Type', default='generic', required=True, tracking=True)
    active = fields.Boolean(default=True)
    company_id = fields.Many2one(
        comodel_name='res.company', string='Company', default=lambda self: self.env.company, index=True)
    last_scanned = fields.Datetime(string='Last Scanned')
    user_id = fields.Many2one(comodel_name='res.users', string='Generated By', default=lambda self: self.env.user, index=True)

    _portal_barcode_name_unique = models.Constraint('unique(name, company_id)', "Barcode already exists for this company.")

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if not vals.get('name'):
                vals['name'] = self.env['ir.sequence'].next_by_code('portal.barcode') or _('New')
        records = super().create(vals_list)
        return records

    def action_deactivate(self):
        for rec in self:
            rec.state = 'inactive'
            rec.active = False

    def action_activate(self):
        for rec in self:
            rec.state = 'active'
            rec.active = True

    @api.model
    def generate_portal_barcode(self, barcode_type='generic', barcode_format='code128'):
        """Service method used by portal controller to generate a new barcode.
        Keeps minimal surface – more complex association logic can be layered later.
        """
        allowed_types = dict(self._fields['barcode_type'].selection)
        if barcode_type not in allowed_types:
            raise ValidationError(_("Invalid barcode type %s") % barcode_type)
        allowed_formats = dict(self._fields['barcode_format'].selection)
        if barcode_format not in allowed_formats:
            raise ValidationError(_("Invalid barcode format %s") % barcode_format)
        rec = self.create({
            'barcode_type': barcode_type,
            'barcode_format': barcode_format,
        })
        return rec
