{
    "name": "Records Management - Enterprise Edition",
    "version": "18.0.11.0.0",
    "category": "Document Management",
    "summary": "Complete Enterprise Records Management System with NAID AAA Compliance",
    "description": """
        Records Management - Enterprise Grade DMS Module
        A comprehensive, enterprise-grade Document Management System (DMS) built for Odoo 18.0.
        This module provides advanced functionality for managing physical document boxes, records,
        shredding services, and compliance tracking with NAID AAA and ISO 15489 standards.
    """,
    "author": "John75SunCity",
    "website": "https://github.com/John75SunCity",
    "license": "LGPL-3",
    "depends": [
        # Core dependencies - REQUIRED
        "base",
        "mail",
        "web",
        "product",
        "stock",
        "account",
        "sale",
        "portal",
        "website",
        "sms",
        "hr",
        "project",
        "industry_fsm",
        "maintenance",
        "fleet",
        "crm",
        # Enterprise apps - only available ones
        "sign",
        "survey",
        "point_of_sale",
        "quality",
        "mrp",
        "purchase",
        "helpdesk",
        "documents",
        "knowledge",
        "planning",
        "timesheet_grid",
        "social",
        "mass_mailing",
        "event",
        "website_event",
        "website_sale",
        "website_blog",
        "website_forum",
        "website_slides",
        "calendar",
        "contacts",
        "board",
        "resource",
        "barcodes",
        "web_tour",
        "web_editor",
        "utm",
        "phone_validation",
        "snailmail",
        "iap",
        "partner_autocomplete",
        "google_calendar",
        "microsoft_calendar",
        "spreadsheet",
        "spreadsheet_dashboard",
        "approvals",
        "voip",
        "lunch",
        "im_livechat",
        "rating",
        "web_unsplash",
        "web_cohort",
        "web_gantt",
        "web_map",
        "digest",
        "gamification",
        "loyalty",
        "payment",
        "payment_stripe",
        "payment_paypal",
        "payment_authorize",
        "payment_adyen",
        "payment_buckaroo",
        "delivery",
        "stock_barcode",
        "stock_landed_costs",
        "sale_management",
        "sale_timesheet",
        "sale_loyalty",
        "purchase_requisition",
        "account_accountant",
        "account_reports",
        "account_budget",
        "account_payment",
        "account_check_printing",
        "account_asset",
        "account_followup",
        "account_inter_company_rules",
        "account_invoice_extract",
        "account_tax_python",
        "account_3way_match",
        "hr_attendance",
        "hr_holidays",
        "hr_timesheet",
        "hr_expense",
        "hr_recruitment",
        "hr_appraisal",
        "hr_payroll",
        "hr_payroll_account",
        "hr_contract",
        "hr_work_entry",
        "hr_work_entry_contract",
        "hr_referral",
        "hr_skills",
        "hr_org_chart",
        "project_timesheet",
        "project_forecast",
        "mrp_workorder",
        "mrp_plm",
        "mrp_mps",
        "mrp_subcontracting",
        "quality_control",
        "quality_mrp",
        "quality_control_worksheet",
        "documents_fleet",
        "documents_hr",
        "documents_project",
        "documents_account",
        "documents_product",
        "documents_sign",
        "documents_spreadsheet",
        "whatsapp",
        "social_facebook",
        "social_twitter",
        "social_linkedin",
        "social_youtube",
        "social_instagram",
        "marketing_automation",
        "website_crm",
        "website_helpdesk",
        "website_hr_recruitment",
        "website_mass_mailing",
        "website_sale_stock",
        "website_sale_wishlist",
        "website_payment",
        "pos_restaurant",
        "pos_discount",
        "pos_loyalty",
        "pos_adyen",
        "pos_stripe",
        "pos_epson_printer",
        "pos_hr",
        "pos_sale",
        "stock_dropshipping",
        "stock_picking_batch",
        "repair",
        "base_address_extended",
        "base_automation",
        "base_geolocalize",
        "base_import",
        "base_setup",
        "bus",
        "http_routing",
        "web_studio",
    ],
    "data": [
        # Security files must load first
        "security/records_management_security.xml",
        "security/additional_models_security.xml",
        "security/intelligent_search_security.xml",
        "security/naid_security.xml",
        "security/portal_request_security.xml",
        "security/ir.model.access.csv",
        # Data files
        "data/ir_sequence_data.xml",
        "data/sequence_data.xml",
        "data/base_rates_container_access_data.xml",
        "data/container_types_base_rates.xml",
        "data/document_retrieval_rates_data.xml",
        "data/feedback_survey_data.xml",
        "data/fsm_automated_actions_data.xml",
        "data/fsm_mail_templates_data.xml",
        "data/intelligent_search_indexes_data.xml",
        "data/load_data.xml",
        "data/mail_activity_data_todo.xml",
        "data/naid_certificate_data.xml",
        "data/naid_compliance_data.xml",
        "data/paper_products_data.xml",
        "data/portal_mail_templates_data.xml",
        "data/products_data.xml",
        "data/scheduled_actions_data.xml",
        "data/storage_fee_data.xml",
        "data/tag_data.xml",
        "data/temp_inventory_configurator_data.xml",
        # Views (load after data)
        "views/enhanced_features_menus.xml",
        "views/advanced_billing_line_views.xml",
        "views/advanced_billing_service_line_views.xml",
        "views/advanced_billing_storage_line_views.xml",
        "views/advanced_billing_views.xml",
        "views/billing_period_views.xml",
        "views/bin_barcode_inventory_views.xml",
        "views/bin_issue_report_wizard_views.xml",
        "views/customer_negotiated_rate_views.xml",
        "views/enhanced_fsm_integration_views.xml",
        "views/fleet_fsm_integration_menus.xml",
        "views/fleet_vehicle_enhanced_views.xml",
        "views/maintenance_request_views.xml",
        "views/mobile_fsm_integration_views.xml",
        "views/fsm_reschedule_wizard_views.xml",
        "views/fsm_notification_manager_views.xml",
        "views/naid_compliance_policy_views.xml",
        "views/naid_custody_views.xml",
        "views/pickup_route_views.xml",
        "views/records_document_flag_permanent_wizard_views.xml",
        "views/records_service_type_views.xml",
        "views/shredding_bin_barcode_wizard_views.xml",
        "views/shredding_service_bin_views.xml",
        "views/shredding_service_event_views.xml",
        "views/workflow_visualization_manager_views.xml",
        # Reports (load last)
        "reports/naid_compliance_policy_report.xml",
    ],
    "demo": [
        "demo/customer_inventory_demo.xml",
        "demo/advanced_billing_demo.xml",
        "demo/model_records_demo.xml",
        "demo/field_label_demo_data.xml",
        "demo/intelligent_search_demo_data.xml",
        "demo/naid_demo_certificates.xml",
        "demo/records_config_mail_templates_data.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "records_management/static/src/scss/records_management.scss",
            "records_management/static/src/css/intelligent_search.css",
            "records_management/static/src/css/system_flowchart.css",
            "records_management/static/src/css/customer_portal_diagram.css",
            "records_management/static/src/js/map_widget.js",
            "records_management/static/src/js/paper_load_progress_field.js",
            "records_management/static/src/js/paper_load_truck_widget.js",
            "records_management/static/src/js/trailer_visualization.js",
            "records_management/static/src/js/truck_widget.js",
            "records_management/static/src/js/field_label_customizer.js",
            "records_management/static/src/js/intelligent_search.js",
            "records_management/static/src/js/system_flowchart_view.js",
            "records_management/static/src/js/customer_portal_diagram_view.js",
            "records_management/static/src/xml/map_widget.xml",
            "records_management/static/src/xml/trailer_visualization.xml",
            "records_management/static/src/xml/intelligent_search_templates.xml",
            "records_management/static/src/xml/system_flowchart_templates.xml",
            "records_management/static/src/xml/customer_portal_diagram_templates.xml",
        ],
        "web.assets_frontend": [
            "records_management/static/src/css/portal_tour.css",
            "records_management/static/src/css/intelligent_search.css",
            "records_management/static/src/css/customer_portal_diagram.css",
            "records_management/static/src/js/portal_tour.js",
            "records_management/static/src/js/portal_docs.js",
            "records_management/static/src/js/portal_inventory_highlights.js",
            "records_management/static/src/js/portal_inventory_search.js",
            "records_management/static/src/js/portal_quote_generator.js",
            "records_management/static/src/js/portal_signature.js",
            "records_management/static/src/js/portal_user_import.js",
            "records_management/static/src/js/intelligent_search.js",
            "records_management/static/src/js/customer_portal_diagram.js",
            "records_management/static/src/xml/intelligent_search_templates.xml",
            "records_management/static/src/xml/customer_portal_diagram_templates.xml",
        ],
    },
    "external_dependencies": {"python": ["qrcode", "pillow"]},
    "installable": True,
    "auto_install": False,
    "application": True,
    "sequence": 100,
    "images": ["static/description/icon.png"],
}
