# -*- coding: utf-8 -*-
{
    'name': 'Records Management - Enterprise Edition',
    'version': '18.0.11.0.0',
    'category': 'Document Management',
    'summary': 'Complete Enterprise Records Management System with NAID AAA Compliance',
    'description': '''
        Records Management - Enterprise Grade DMS Module
        A comprehensive, enterprise-grade Document Management System (DMS) built for Odoo 18.0.
        This module provides advanced functionality for managing physical document boxes, records,
        shredding services, and compliance tracking with NAID AAA and ISO 15489 standards.
    ''',
    'author': 'John75SunCity',
    'website': 'https://github.com/John75SunCity',
    'license': 'LGPL-3',
    'depends': [
        'base', 'mail', 'web', 'product', 'stock', 'account', 'sale', 'purchase',
        'portal', 'website', 'point_of_sale', 'sms', 'survey',
        'hr', 'project', 'industry_fsm', 'maintenance', 'fleet', 'crm',
        'sale_management', 'website_sale'
    ],
    "data": [
        "data/advanced_billing_demo.xml",
        "data/base_rates_container_access_data.xml",
        "data/document_retrieval_rates_data.xml",
        "data/feedback_survey_data.xml",
        "data/field_label_demo_data.xml",
        "data/fsm_automated_actions_data.xml",
        "data/fsm_mail_templates_data.xml",
        "data/intelligent_search_demo_data.xml",
        "data/intelligent_search_indexes_data.xml",
        "data/ir_sequence_data.xml",
        "data/load_data.xml",
        "data/mail_activity_data_todo.xml",
        "data/model_external_ids.xml",
        "data/model_records_demo.xml",
        "data/naid_certificate_data.xml",
        "data/naid_compliance_data.xml",
        "data/paper_products_data.xml",
        "data/portal_mail_templates_data.xml",
        "data/products_data.xml",
        "data/records_config_mail_templates_data.xml",
        "data/scheduled_actions_data.xml",
        "data/sequence_data.xml",
        "data/storage_fee_data.xml",
        "data/tag_data.xml",
        "data/temp_inventory_configurator_data.xml",
        "data/temp_inventory_sequence_data.xml",
        "data/user_setup_data.xml",
        "security/records_management_security.xml",  # Renamed from records_management_security.xml to follow convention
        "security/ir.model.access.csv",
        "views/advanced_billing_line_views.xml",
        "views/advanced_billing_service_line_views.xml",
        "views/advanced_billing_storage_line_views.xml",
        "views/advanced_billing_views.xml",
        "views/billing_period_views.xml",
        "views/bin_issue_report_wizard_views.xml",
        "views/customer_negotiated_rate_views.xml",
        "views/fleet_fsm_integration_menus.xml",
        "views/fleet_vehicle_enhanced_views.xml",
        "views/maintenance_request_views.xml",
        "views/naid_custody_views.xml",
        "views/pickup_route_views.xml",
        "views/records_document_flag_permanent_wizard_views.xml",
        "views/records_management_dashboard_view.xml",
        "views/records_management_dashboard.xml",
        "views/records_management_document_view.xml",
        "views/records_management_form.xml",
        "views/records_management_menu.xml",
        "views/records_management_settings_view.xml",
        "views/records_management_shredding_view.xml",
        "views/records_management_tree.xml",
        "views/records_service_type_views.xml",
        "views/shredding_bin_barcode_wizard_views.xml",
        "views/shredding_service_bin_views.xml",
        "views/shredding_service_event_views.xml",
        "reports/account_move_line_reports.xml",
        "reports/additional_reports.xml",
        "reports/customer_negotiated_rate_report.xml",
        "reports/maintenance_request_report.xml",
        "reports/naid_custody_report.xml",
        "reports/records_service_type_report.xml",
        "reports/shredding_bin_barcode_wizard_report.xml",
        "reports/shredding_service_bin_report.xml",
        "reports/shredding_service_event_report.xml",
        "reports/shredding_service_report.xml",
        "templates/records_dashboard_templates.xml",
        "templates/records_management_dashboard_templates.xml",
        "templates/records_management_portal_templates.xml",
        "templates/records_portal_templates.xml"
    ],
    'demo': [
        'demo/demo_records.xml'
    ],
    'assets': {
        'web.assets_backend': [
            'records_management/static/src/lib/vis/vis-network.min.js',
            'records_management/static/src/lib/vis/vis-network.min.css',
            'records_management/static/src/scss/records_management.scss',
            'records_management/static/src/js/map_widget.js',
            'records_management/static/src/js/paper_load_progress_field.js',
            'records_management/static/src/js/paper_load_truck_widget.js',
            'records_management/static/src/js/trailer_visualization.js',
            'records_management/static/src/js/truck_widget.js',
            'records_management/static/src/js/field_label_customizer.js',
            'records_management/static/src/js/intelligent_search.js',
            'records_management/static/src/css/intelligent_search.css',
            'records_management/static/src/js/system_flowchart_view.js',
            'records_management/static/src/css/system_flowchart.css',
            'records_management/static/src/js/customer_portal_diagram_view.js',
            'records_management/static/src/css/customer_portal_diagram.css',
            'records_management/static/src/xml/map_widget.xml',
            'records_management/static/src/xml/trailer_visualization.xml',
            'records_management/static/src/xml/intelligent_search_templates.xml',
            'records_management/static/src/xml/system_flowchart_templates.xml',
            'records_management/static/src/xml/customer_portal_diagram_templates.xml'
        ],
        'web.assets_frontend': [
            'records_management/static/src/lib/vis/vis-network.min.js',
            'records_management/static/src/lib/vis/vis-network.min.css',
            'records_management/static/src/css/portal_tour.css',
            'records_management/static/src/css/intelligent_search.css',
            'records_management/static/src/js/portal_tour.js',
            'records_management/static/src/js/portal_docs.js',
            'records_management/static/src/js/portal_inventory_highlights.js',
            'records_management/static/src/js/portal_inventory_search.js',
            'records_management/static/src/js/portal_quote_generator.js',
            'records_management/static/src/js/portal_signature.js',
            'records_management/static/src/js/portal_user_import.js',
            'records_management/static/src/js/intelligent_search.js',
            'records_management/static/src/js/customer_portal_diagram.js',
            'records_management/static/src/css/customer_portal_diagram.css',
            'records_management/static/src/xml/intelligent_search_templates.xml',
            'records_management/static/src/xml/customer_portal_diagram_templates.xml'
        ]
    },
    'external_dependencies': {
        'python': ['qrcode', 'pillow']
    },
    'installable': True,
    'auto_install': False,
    'application': True,
    'sequence': 100,
    'images': ['static/description/icon.png']
}
