name: Auto-sync working branch to main

on:
  push:
    branches: [ Enterprise-Grade-DMS-Module-Records-Management ]

jobs:
  sync-to-main:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
    
    - name: Sync to main branch
      run: |
        echo "🔄 Syncing Enterprise-Grade-DMS-Module-Records-Management to main..."
        git checkout main
        git merge --ff-only Enterprise-Grade-DMS-Module-Records-Management
        git push origin main
        echo "✅ Main branch updated successfully!"
    
    - name: Return to working branch
      run: |
        git checkout Enterprise-Grade-DMS-Module-Records-Management
        echo "📋 Sync completed. Both branches are now in sync."
